### ISSUE TITLE
Большое количество записей

### ISSUE THREAD

**Issue by foxygood** [wnull/VKStatic#1]
Привет, сегодня использовав библиотеку столкнулся с такой проблемой. Если попробовать сканировать стену, где больше 10k записей, то выдает постоянно ошибку (слишком много запросов) , так и не показав результата, как быть?

**Comment by wnull** [comment]
Добрый вечер, пока думаем как сделать красиво реализацию скрипта, постепенно в ближайших обновлениях эта проблема будет решаться, спасибо за помощь в тестировании)

**Comment by foxygood** [comment]
Надеюсь это исправится, хотелось бы использовать эту библиотеку для команды бота, еще раз спасибо, будем ждать.
